// <auto-generated />
using System;
using AppTrack.Persistance.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppTrack.Persistance.Migrations
{
    [DbContext(typeof(AppTrackDatabaseContext))]
    [Migration("20260423193545_UpdateChatModelsSeedData")]
    partial class UpdateChatModelsSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppTrack.Domain.AiSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SelectedChatModelId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AiSettings");
                });

            modelBuilder.Entity("AppTrack.Domain.BuiltInPrompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BuiltInPrompts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "builtIn_GenerateApplicationText",
                            PromptTemplate = "Here is my resume. Using the information you gather from it, please write a brief and professional email for the following job posting that explains why I am the perfect freelancer for this position. Only reference skills and experience explicitly listed in my CV and skills below. Do not add any skills from the job posting that are not in my profile.\n\nMy personal data:\nMy CV: {{builtIn_CvText}}\nMy Name: {{builtIn_FirstName}} {{builtIn_LastName}}\nMy Hourly Rate: {{builtIn_HourlyRate}}\nMy Daily Rate: {{builtIn_DailyRate}}\nMy Skills: {{builtIn_Skills}}\nMy Work Mode: {{builtIn_WorkMode}}\nAvailable From: {{builtIn_AvailableFrom}}\n\nJob posting:\nJob Description: {{JobDescription}}\nContact Person: {{ContactPerson}}\nPosition: {{Position}}"
                        },
                        new
                        {
                            Id = 2,
                            Name = "builtIn_JobMatchAnalysis",
                            PromptTemplate = "Analyze how well my profile matches the following job posting. Be honest and direct — do NOT inflate the match score or soften weaknesses. If I am missing required skills, say so explicitly.\n\nYour response must cover:\n1. Match score: A percentage (0–100) with a one-sentence justification\n2. Skills I have that match: Reference my CV and skills list specifically\n3. Skills or experience I am missing: Be specific — what does the job require that I lack?\n4. Work mode / location fit: Is {{Location}} compatible with my preferred work mode ({{builtIn_WorkMode}})?\n5. Verdict: Should I apply? What are the main risks or gaps I would need to address?\n\nMy profile:\nCV: {{builtIn_CvText}}\nSkills: {{builtIn_Skills}}\nWork Mode Preference: {{builtIn_WorkMode}}\n\nJob posting:\nPosition: {{Position}}\nLocation: {{Location}}\nDuration: {{DurationInMonths}} months\nStart Date: {{StartDate}}\nJob Description: {{JobDescription}}"
                        },
                        new
                        {
                            Id = 3,
                            Name = "builtIn_InterviewPrep",
                            PromptTemplate = "Prepare me for an interview for the {{Position}} role. Base all questions strictly on the job description — do not generate generic filler questions.\n\nProvide:\n1. 5–7 role-specific or technical questions the interviewer is likely to ask based on the actual requirements\n2. 2–3 behavioral questions relevant to this type of role\n3. For each question: a suggested answer approach based on my CV and skills. If my experience in a relevant area is weak, say so explicitly and suggest how to address it honestly rather than inventing strengths\n4. 2 questions I should ask the interviewer to evaluate whether this project is genuinely worth taking\n\nMy profile:\nMy Name: {{builtIn_FirstName}} {{builtIn_LastName}}\nMy CV: {{builtIn_CvText}}\nMy Skills: {{builtIn_Skills}}\n\nJob posting:\nPosition: {{Position}}\nLocation: {{Location}}\nDuration: {{DurationInMonths}} months\nStart Date: {{StartDate}}\nJob Description: {{JobDescription}}"
                        },
                        new
                        {
                            Id = 4,
                            Name = "builtIn_RateAnalysis",
                            PromptTemplate = "Based on the job description and my CV, analyze what daily and hourly rate I can realistically charge for this role.\n\nYour response must include:\n1. Recommended rate range: A realistic daily rate range (minimum / target / optimal) I can ask for given my qualifications and the role requirements\n2. Justification: Why this range — reference specific skills from my CV that match or strengthen my position, and be honest about any gaps that would weaken it\n3. Minimum rate: The lowest daily rate I should accept for this role without underselling myself — explain why going below this would not be appropriate\n4. Rate risk factors: Are there aspects of my profile (e.g. missing skills, overqualification, location/remote constraints) that could affect what I can realistically negotiate?\n\nBe honest and direct. If my qualifications do not fully match the role, reflect that in a lower range rather than inflating the recommendation.\n\nMy profile:\nMy CV: {{builtIn_CvText}}\nMy Skills: {{builtIn_Skills}}\nMy Current Daily Rate: {{builtIn_DailyRate}}\nMy Current Hourly Rate: {{builtIn_HourlyRate}}\nWork Mode: {{builtIn_WorkMode}}\n\nJob posting:\nPosition: {{Position}}\nLocation: {{Location}}\nDuration: {{DurationInMonths}} months\nStart Date: {{StartDate}}\nJob Description: {{JobDescription}}"
                        });
                });

            modelBuilder.Entity("AppTrack.Domain.BuiltInPromptParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiSettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AiSettingsId", "Key")
                        .IsUnique();

                    b.ToTable("BuiltInPromptParameter");
                });

            modelBuilder.Entity("AppTrack.Domain.ChatModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ChatModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiModelName = "gpt-3.5-turbo",
                            Description = "Legacy model. Not recommended for CV analysis or job matching due to limited reasoning capabilities.",
                            IsActive = false,
                            Name = "ChatGPT 3.5"
                        },
                        new
                        {
                            Id = 2,
                            ApiModelName = "gpt-4",
                            Description = "High-quality model for complex analysis, CV parsing, job matching and advanced reasoning. Recommended for accurate evaluations and structured outputs.",
                            IsActive = false,
                            Name = "ChatGPT 4"
                        },
                        new
                        {
                            Id = 3,
                            ApiModelName = "gpt-4o",
                            Description = "Best balance of quality and speed, ideal for CV analysis, job matching and complex reasoning",
                            IsActive = true,
                            Name = "GPT-4o"
                        },
                        new
                        {
                            Id = 4,
                            ApiModelName = "gpt-4o-mini",
                            Description = "Fast and cost-efficient model for simple tasks like rephrasing, summaries, and draft generation. Not suitable for deep analysis.",
                            IsActive = true,
                            Name = "ChatGPT 4 Mini"
                        },
                        new
                        {
                            Id = 5,
                            ApiModelName = "gpt-5",
                            Description = "Top-tier reasoning model for critical evaluations and high-stakes decisions",
                            IsActive = true,
                            Name = "GPT-5"
                        });
                });

            modelBuilder.Entity("AppTrack.Domain.FreelancerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CvBlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CvFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CvText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CvUploadDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DailyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Skills")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WorkMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FreelancerProfiles");
                });

            modelBuilder.Entity("AppTrack.Domain.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DurationInMonths")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("AppTrack.Domain.JobApplicationAiText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId", "PromptKey");

                    b.ToTable("JobApplicationAiTexts", (string)null);
                });

            modelBuilder.Entity("AppTrack.Domain.JobApplicationDefaults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobApplicationDefaults");
                });

            modelBuilder.Entity("AppTrack.Domain.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiSettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AiSettingsId", "Name")
                        .IsUnique();

                    b.ToTable("Prompt");
                });

            modelBuilder.Entity("AppTrack.Domain.PromptParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AISettingsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AISettingsId", "Key")
                        .IsUnique();

                    b.ToTable("PromptParameter");
                });

            modelBuilder.Entity("AppTrack.Domain.BuiltInPromptParameter", b =>
                {
                    b.HasOne("AppTrack.Domain.AiSettings", "AiSettings")
                        .WithMany("BuiltInPromptParameter")
                        .HasForeignKey("AiSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSettings");
                });

            modelBuilder.Entity("AppTrack.Domain.JobApplicationAiText", b =>
                {
                    b.HasOne("AppTrack.Domain.JobApplication", "JobApplication")
                        .WithMany("AiTextHistory")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("AppTrack.Domain.Prompt", b =>
                {
                    b.HasOne("AppTrack.Domain.AiSettings", "AiSettings")
                        .WithMany("Prompts")
                        .HasForeignKey("AiSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSettings");
                });

            modelBuilder.Entity("AppTrack.Domain.PromptParameter", b =>
                {
                    b.HasOne("AppTrack.Domain.AiSettings", "AISettings")
                        .WithMany("PromptParameter")
                        .HasForeignKey("AISettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AISettings");
                });

            modelBuilder.Entity("AppTrack.Domain.AiSettings", b =>
                {
                    b.Navigation("BuiltInPromptParameter");

                    b.Navigation("PromptParameter");

                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("AppTrack.Domain.JobApplication", b =>
                {
                    b.Navigation("AiTextHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
