name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  # ------------------------------
  # Job 1: Windows Build (WPF)
  # ------------------------------
  build-windows:
    name: Build WPF & Windows Projects
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

  # ------------------------------
  # Job 2: Linux Build + Integration Tests
  # ------------------------------
  integration-tests:
    name: Run Integration Tests with Testcontainers
    runs-on: ubuntu-latest
    needs: build-windows
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "Test1234!"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build projects (API, Application, Persistence)
        run: |
          dotnet build AppTrack.Api/AppTrack.Api.csproj --no-restore --configuration Release
          dotnet build AppTrack.Application/AppTrack.Application.csproj --no-restore --configuration Release
          dotnet build AppTrack.Persistance/AppTrack.Persistance.csproj --no-restore --configuration Release

      - name: Run Unit Tests
          run: dotnet test AppTrack.Application.UnitTests/AppTrack.Application.UnitTests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=unit-tests.trx"

      - name: Run Persistence Integration Tests
          run: dotnet test AppTrack.Persistance.IntegrationTests/AppTrack.Persistance.IntegrationTests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=persistence-integration-tests.trx"

      - name: Run API Integration Tests
          run: dotnet test AppTrack.Api.IntegrationTests/AppTrack.Api.IntegrationTests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=api-integration-tests.trx"

